/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PianoV2;

import javax.swing.JFrame;
import org.jfugue.player.Player;

/**
 *
 * @author messi
 */
public class piano extends javax.swing.JFrame {
Player reproductor = new Player();
    public piano() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        BtnDo = new javax.swing.JButton();
        BtnMi = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        BtnRe = new javax.swing.JButton();
        BtnFa = new javax.swing.JButton();
        BtnSol = new javax.swing.JButton();
        BtnLa = new javax.swing.JButton();
        BtnSi = new javax.swing.JButton();
        BtnRe2 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        BtnDo2 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        BtnSi3 = new javax.swing.JButton();
        BtnMi2 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        BtnFa2 = new javax.swing.JButton();
        BtnSol2 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        BtnLa2 = new javax.swing.JButton();
        BtnSi2 = new javax.swing.JButton();
        BtnDo3 = new javax.swing.JButton();
        BtnRe3 = new javax.swing.JButton();
        BtnMi3 = new javax.swing.JButton();
        BtnFa3 = new javax.swing.JButton();
        BtnSol3 = new javax.swing.JButton();
        BtnLa3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 8));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 340));
        jPanel1.setPreferredSize(new java.awt.Dimension(830, 830));
        jPanel1.setLayout(null);

        jButton8.setBackground(java.awt.Color.black);
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton8.setText("D#");
        jButton8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(440, 90, 50, 120);

        jButton9.setBackground(java.awt.Color.black);
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton9.setText("F#");
        jButton9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(530, 90, 50, 120);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton2.setText("C#");
        jButton2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(30, 90, 47, 120);

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton5.setText("D#");
        jButton5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(90, 90, 49, 120);

        jButton7.setBackground(java.awt.Color.black);
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton7.setText("C#");
        jButton7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(380, 90, 50, 120);

        jButton6.setBackground(java.awt.Color.black);
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setText("B#");
        jButton6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(300, 90, 50, 120);

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("G#");
        jButton4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(240, 90, 49, 120);

        BtnDo.setBackground(java.awt.Color.white);
        BtnDo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnDo.setText("Do");
        BtnDo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnDo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnDoMousePressed(evt);
            }
        });
        BtnDo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDoActionPerformed(evt);
            }
        });
        jPanel1.add(BtnDo);
        BtnDo.setBounds(10, 90, 50, 240);

        BtnMi.setBackground(java.awt.Color.white);
        BtnMi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnMi.setText("Mi");
        BtnMi.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnMi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMiActionPerformed(evt);
            }
        });
        jPanel1.add(BtnMi);
        BtnMi.setBounds(110, 90, 50, 240);

        jButton1.setBackground(java.awt.Color.black);
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("F#");
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(180, 90, 50, 120);

        BtnRe.setBackground(java.awt.Color.white);
        BtnRe.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnRe.setText("Re");
        BtnRe.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnRe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReActionPerformed(evt);
            }
        });
        jPanel1.add(BtnRe);
        BtnRe.setBounds(60, 90, 50, 240);

        BtnFa.setBackground(java.awt.Color.white);
        BtnFa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnFa.setText("Fa");
        BtnFa.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnFa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFaActionPerformed(evt);
            }
        });
        jPanel1.add(BtnFa);
        BtnFa.setBounds(160, 90, 50, 240);

        BtnSol.setBackground(java.awt.Color.white);
        BtnSol.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnSol.setText("Sol");
        BtnSol.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnSol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSolActionPerformed(evt);
            }
        });
        jPanel1.add(BtnSol);
        BtnSol.setBounds(210, 90, 50, 240);

        BtnLa.setBackground(java.awt.Color.white);
        BtnLa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnLa.setText("La");
        BtnLa.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnLa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLaActionPerformed(evt);
            }
        });
        jPanel1.add(BtnLa);
        BtnLa.setBounds(260, 90, 50, 240);

        BtnSi.setBackground(java.awt.Color.white);
        BtnSi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnSi.setText("Si");
        BtnSi.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSiActionPerformed(evt);
            }
        });
        jPanel1.add(BtnSi);
        BtnSi.setBounds(310, 90, 50, 240);

        BtnRe2.setBackground(java.awt.Color.white);
        BtnRe2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnRe2.setText("Re");
        BtnRe2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnRe2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRe2ActionPerformed(evt);
            }
        });
        jPanel1.add(BtnRe2);
        BtnRe2.setBounds(410, 90, 50, 240);

        jButton13.setBackground(java.awt.Color.black);
        jButton13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton13.setText("D#");
        jButton13.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jButton13);
        jButton13.setBounds(790, 90, 50, 120);

        BtnDo2.setBackground(java.awt.Color.white);
        BtnDo2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnDo2.setText("Do");
        BtnDo2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnDo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDo2ActionPerformed(evt);
            }
        });
        jPanel1.add(BtnDo2);
        BtnDo2.setBounds(360, 90, 50, 240);

        jButton11.setBackground(java.awt.Color.black);
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton11.setText("B#");
        jButton11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11);
        jButton11.setBounds(650, 90, 50, 120);

        jButton12.setBackground(new java.awt.Color(0, 0, 0));
        jButton12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton12.setText("C#");
        jButton12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jButton12);
        jButton12.setBounds(730, 90, 50, 120);

        jButton16.setBackground(java.awt.Color.black);
        jButton16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton16.setText("B#");
        jButton16.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jButton16);
        jButton16.setBounds(1000, 90, 50, 120);

        BtnSi3.setBackground(java.awt.Color.white);
        BtnSi3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnSi3.setText("Si");
        BtnSi3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnSi3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSi3ActionPerformed(evt);
            }
        });
        jPanel1.add(BtnSi3);
        BtnSi3.setBounds(1010, 90, 50, 240);

        BtnMi2.setBackground(java.awt.Color.white);
        BtnMi2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnMi2.setText("Mi");
        BtnMi2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnMi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMi2ActionPerformed(evt);
            }
        });
        jPanel1.add(BtnMi2);
        BtnMi2.setBounds(460, 90, 50, 240);

        jButton10.setBackground(java.awt.Color.black);
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton10.setText("G#");
        jButton10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);
        jButton10.setBounds(590, 90, 50, 120);

        BtnFa2.setBackground(java.awt.Color.white);
        BtnFa2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnFa2.setText("Fa");
        BtnFa2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnFa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFa2ActionPerformed(evt);
            }
        });
        jPanel1.add(BtnFa2);
        BtnFa2.setBounds(510, 90, 50, 240);

        BtnSol2.setBackground(java.awt.Color.white);
        BtnSol2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnSol2.setText("Sol");
        BtnSol2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnSol2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSol2ActionPerformed(evt);
            }
        });
        jPanel1.add(BtnSol2);
        BtnSol2.setBounds(560, 90, 50, 240);

        jButton15.setBackground(java.awt.Color.black);
        jButton15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton15.setText("G#");
        jButton15.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15);
        jButton15.setBounds(940, 90, 50, 120);

        jButton14.setBackground(java.awt.Color.black);
        jButton14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton14.setText("F#");
        jButton14.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14);
        jButton14.setBounds(880, 90, 50, 120);

        BtnLa2.setBackground(java.awt.Color.white);
        BtnLa2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnLa2.setText("La");
        BtnLa2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnLa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLa2ActionPerformed(evt);
            }
        });
        jPanel1.add(BtnLa2);
        BtnLa2.setBounds(610, 90, 50, 240);

        BtnSi2.setBackground(java.awt.Color.white);
        BtnSi2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnSi2.setText("Si");
        BtnSi2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnSi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSi2ActionPerformed(evt);
            }
        });
        jPanel1.add(BtnSi2);
        BtnSi2.setBounds(660, 90, 50, 240);

        BtnDo3.setBackground(java.awt.Color.white);
        BtnDo3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnDo3.setText("Do");
        BtnDo3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnDo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDo3ActionPerformed(evt);
            }
        });
        jPanel1.add(BtnDo3);
        BtnDo3.setBounds(710, 90, 50, 240);

        BtnRe3.setBackground(java.awt.Color.white);
        BtnRe3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnRe3.setText("Re");
        BtnRe3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnRe3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRe3ActionPerformed(evt);
            }
        });
        jPanel1.add(BtnRe3);
        BtnRe3.setBounds(760, 90, 50, 240);

        BtnMi3.setBackground(java.awt.Color.white);
        BtnMi3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnMi3.setText("Mi");
        BtnMi3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnMi3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMi3ActionPerformed(evt);
            }
        });
        jPanel1.add(BtnMi3);
        BtnMi3.setBounds(810, 90, 50, 240);

        BtnFa3.setBackground(java.awt.Color.white);
        BtnFa3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnFa3.setText("Fa");
        BtnFa3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnFa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFa3ActionPerformed(evt);
            }
        });
        jPanel1.add(BtnFa3);
        BtnFa3.setBounds(860, 90, 50, 240);

        BtnSol3.setBackground(java.awt.Color.white);
        BtnSol3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnSol3.setText("Sol");
        BtnSol3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnSol3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSol3ActionPerformed(evt);
            }
        });
        jPanel1.add(BtnSol3);
        BtnSol3.setBounds(910, 90, 50, 240);

        BtnLa3.setBackground(java.awt.Color.white);
        BtnLa3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnLa3.setText("La");
        BtnLa3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnLa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLa3ActionPerformed(evt);
            }
        });
        jPanel1.add(BtnLa3);
        BtnLa3.setBounds(960, 90, 50, 240);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Marco Antonio Martinez Olivares");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 380, 22);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 20, 1090, 340);

        setBounds(0, 0, 1129, 422);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        Sonido_Hilo tocar = new Sonido_Hilo(reproductor, "37iii");
       tocar.start();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       Sonido_Hilo tocar = new Sonido_Hilo(reproductor, "39iii");
           tocar.start();
       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void BtnSi3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSi3ActionPerformed
       Sonido_Hilo tocar = new Sonido_Hilo(reproductor, "B5iiii");
           tocar.start();
        
    }//GEN-LAST:event_BtnSi3ActionPerformed

    private void BtnMiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMiActionPerformed
     Sonido_Hilo tocar = new Sonido_Hilo(reproductor, "E3iiiii");
            tocar.start();  
        
       
    }//GEN-LAST:event_BtnMiActionPerformed

    private void BtnDoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDoActionPerformed
           Sonido_Hilo tocar = new Sonido_Hilo(reproductor, "36iiii");
            tocar.start();
            
            
       
    }//GEN-LAST:event_BtnDoActionPerformed

    private void BtnReActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReActionPerformed
           
         Sonido_Hilo tocar = new Sonido_Hilo(reproductor, "D3iiii");
            tocar.start();
      
    }//GEN-LAST:event_BtnReActionPerformed

    private void BtnFaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFaActionPerformed
         Sonido_Hilo tocar = new Sonido_Hilo(reproductor, "F3iiii");
            tocar.start();  
       
    }//GEN-LAST:event_BtnFaActionPerformed

    private void BtnSolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSolActionPerformed
          Sonido_Hilo tocar = new Sonido_Hilo(reproductor, "G3iiii");
            tocar.start();
        
    }//GEN-LAST:event_BtnSolActionPerformed

    private void BtnLaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLaActionPerformed
       Sonido_Hilo tocar = new Sonido_Hilo(reproductor, "A3iiii");
            tocar.start();
    
    }//GEN-LAST:event_BtnLaActionPerformed

    private void BtnSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSiActionPerformed
         Sonido_Hilo tocar = new Sonido_Hilo(reproductor, "B3iii");
            tocar.start();
            
        
      
    }//GEN-LAST:event_BtnSiActionPerformed

    private void BtnDo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDo2ActionPerformed
          Sonido_Hilo tocar = new Sonido_Hilo(reproductor, "C4iiii");
           tocar.start();
        

    }//GEN-LAST:event_BtnDo2ActionPerformed

    private void BtnRe2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRe2ActionPerformed
       Sonido_Hilo tocar = new Sonido_Hilo(reproductor, "D4iiii");
           tocar.start();
  
    }//GEN-LAST:event_BtnRe2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Sonido_Hilo tocar = new Sonido_Hilo(reproductor, "42iii");
           tocar.start();
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtnMi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMi2ActionPerformed
        Sonido_Hilo tocar = new Sonido_Hilo(reproductor, "E4iiii");
           tocar.start(); 
   
    }//GEN-LAST:event_BtnMi2ActionPerformed

    private void BtnFa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFa2ActionPerformed
        Sonido_Hilo tocar = new Sonido_Hilo(reproductor, "F4iiii");
           tocar.start();
       
    }//GEN-LAST:event_BtnFa2ActionPerformed

    private void BtnSol2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSol2ActionPerformed
      Sonido_Hilo tocar = new Sonido_Hilo(reproductor, "G4iiii");
           tocar.start();
       
    }//GEN-LAST:event_BtnSol2ActionPerformed

    private void BtnLa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLa2ActionPerformed
        Sonido_Hilo tocar = new Sonido_Hilo(reproductor, "A4iiii");
           tocar.start();

    }//GEN-LAST:event_BtnLa2ActionPerformed

    private void BtnSi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSi2ActionPerformed
      Sonido2 tocar = new Sonido2(reproductor, "B4iiii");
           tocar.start();
        
        
    }//GEN-LAST:event_BtnSi2ActionPerformed

    private void BtnDo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDo3ActionPerformed
        Sonido_Hilo tocar = new Sonido_Hilo(reproductor, "C5iiiii");
           tocar.start();
        
    }//GEN-LAST:event_BtnDo3ActionPerformed

    private void BtnRe3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRe3ActionPerformed
       Sonido2 tocar = new Sonido2(reproductor, "D5iiiii");
           tocar.start();
        
      
    }//GEN-LAST:event_BtnRe3ActionPerformed

    private void BtnMi3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMi3ActionPerformed
        Sonido_Hilo tocar = new Sonido_Hilo(reproductor, "E5iiiii");
           tocar.start();
       
    }//GEN-LAST:event_BtnMi3ActionPerformed

    private void BtnFa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFa3ActionPerformed
       Sonido2 tocar = new Sonido2(reproductor, "F5iiiii");
           tocar.start();
       
    }//GEN-LAST:event_BtnFa3ActionPerformed

    private void BtnSol3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSol3ActionPerformed
       Sonido_Hilo tocar = new Sonido_Hilo(reproductor, "G5iiiii");
           tocar.start();
      
    }//GEN-LAST:event_BtnSol3ActionPerformed

    private void BtnLa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLa3ActionPerformed
        Sonido_Hilo tocar = new Sonido_Hilo(reproductor, "A5iiiii");
           tocar.start();
        
    }//GEN-LAST:event_BtnLa3ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        Sonido_Hilo tocar = new Sonido_Hilo(reproductor, "54iiii");
           tocar.start();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       Sonido_Hilo tocar = new Sonido_Hilo(reproductor, "44iiii");
           tocar.start();
   
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Sonido_Hilo tocar = new Sonido_Hilo(reproductor, "46iiii");
           tocar.start();
       
    }//GEN-LAST:event_jButton6ActionPerformed

    private void BtnDoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnDoMousePressed
     
    }//GEN-LAST:event_BtnDoMousePressed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Sonido_Hilo tocar = new Sonido_Hilo(reproductor, "49iiii");
           tocar.start();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       Sonido_Hilo tocar = new Sonido_Hilo(reproductor, "51iiii");
           tocar.start();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       Sonido_Hilo tocar = new Sonido_Hilo(reproductor, "56iiii");
           tocar.start();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
       Sonido_Hilo tocar = new Sonido_Hilo(reproductor, "58iiii");
           tocar.start();
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new piano().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDo;
    private javax.swing.JButton BtnDo2;
    private javax.swing.JButton BtnDo3;
    private javax.swing.JButton BtnFa;
    private javax.swing.JButton BtnFa2;
    private javax.swing.JButton BtnFa3;
    private javax.swing.JButton BtnLa;
    private javax.swing.JButton BtnLa2;
    private javax.swing.JButton BtnLa3;
    private javax.swing.JButton BtnMi;
    private javax.swing.JButton BtnMi2;
    private javax.swing.JButton BtnMi3;
    private javax.swing.JButton BtnRe;
    private javax.swing.JButton BtnRe2;
    private javax.swing.JButton BtnRe3;
    private javax.swing.JButton BtnSi;
    private javax.swing.JButton BtnSi2;
    private javax.swing.JButton BtnSi3;
    private javax.swing.JButton BtnSol;
    private javax.swing.JButton BtnSol2;
    private javax.swing.JButton BtnSol3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
